/**
 * Static knowledge base backing the built-in (no-API-key) fallback engine.
 * Also used to validate AI output titles against known roles.
 */

export const SKILL_SYNONYMS = {
  js: 'javascript',
  javascript: 'javascript',
  ts: 'typescript',
  react: 'react',
  node: 'node.js',
  nodejs: 'node.js',
  'node.js': 'node.js',
  expressjs: 'express',
  mongo: 'mongodb',
  postgres: 'postgresql',
  psql: 'postgresql',
  ml: 'machine learning',
  'machine-learning': 'machine learning',
  dl: 'deep learning',
  pytorch: 'pytorch',
  tf: 'tensorflow',
  k8s: 'kubernetes',
  aws: 'aws',
  gcp: 'google cloud',
  'google cloud': 'google cloud',
  ci: 'ci/cd',
  cicd: 'ci/cd',
  'ci/cd': 'ci/cd',
  pandas: 'pandas',
  powerbi: 'power bi',
  'power bi': 'power bi',
  photoshop: 'photoshop',
  'ui/ux': 'ui/ux design',
  ux: 'ui/ux design',
  ui: 'ui/ux design',
  figma: 'figma',
  seo: 'seo',
};

export const CAREERS = [
  {
    title: 'Frontend Developer',
    description: 'Builds the user-facing layer of web applications — interfaces, interactions and performance.',
    skills: ['html', 'css', 'javascript', 'react', 'typescript', 'responsive design', 'git', 'tailwind', 'next.js', 'redux'],
    salaryRange: '₹4–10 LPA entry (India)',
    demand: 'High',
    interests: ['web development', 'design', 'frontend', 'ui', 'coding'],
  },
  {
    title: 'Backend Developer',
    description: 'Designs server-side logic, APIs, databases and the systems behind the product.',
    skills: ['node.js', 'express', 'mongodb', 'postgresql', 'sql', 'python', 'java', 'rest apis', 'redis', 'docker', 'git'],
    salaryRange: '₹4–12 LPA entry (India)',
    demand: 'High',
    interests: ['backend', 'databases', 'api', 'system design', 'coding'],
  },
  {
    title: 'Full-Stack Developer',
    description: 'Ships end-to-end features across frontend and backend, common in startups.',
    skills: ['javascript', 'react', 'node.js', 'express', 'mongodb', 'sql', 'git', 'html', 'css', 'typescript', 'rest apis'],
    salaryRange: '₹4–12 LPA entry (India)',
    demand: 'High',
    interests: ['web development', 'startups', 'coding', 'full stack', 'mern'],
  },
  {
    title: 'Data Analyst',
    description: 'Turns raw data into dashboards, reports and business recommendations.',
    skills: ['sql', 'excel', 'python', 'pandas', 'power bi', 'tableau', 'statistics', 'data visualization'],
    salaryRange: '₹3.5–8 LPA entry (India)',
    demand: 'High',
    interests: ['data', 'analytics', 'business', 'statistics'],
  },
  {
    title: 'Data Scientist',
    description: 'Applies statistics and machine learning to predict, classify and explain outcomes.',
    skills: ['python', 'machine learning', 'pandas', 'numpy', 'statistics', 'scikit-learn', 'sql', 'data visualization', 'deep learning'],
    salaryRange: '₹6–15 LPA entry (India)',
    demand: 'High',
    interests: ['data science', 'machine learning', 'ai', 'statistics', 'math'],
  },
  {
    title: 'Machine Learning Engineer',
    description: 'Productionizes ML models into scalable, reliable systems.',
    skills: ['python', 'machine learning', 'deep learning', 'pytorch', 'tensorflow', 'mlops', 'docker', 'aws', 'sql'],
    salaryRange: '₹6–18 LPA entry (India)',
    demand: 'Growing',
    interests: ['machine learning', 'ai', 'mlops', 'engineering'],
  },
  {
    title: 'AI / LLM Engineer',
    description: 'Builds products on top of large language models — RAG pipelines, agents and prompt systems.',
    skills: ['python', 'llms', 'langchain', 'nlp', 'pytorch', 'prompt engineering', 'machine learning', 'rest apis'],
    salaryRange: '₹6–20 LPA entry (India)',
    demand: 'Growing',
    interests: ['ai', 'llm', 'chatgpt', 'generative ai', 'machine learning'],
  },
  {
    title: 'DevOps / Cloud Engineer',
    description: 'Automates infrastructure, deployments and reliability for software teams.',
    skills: ['linux', 'docker', 'kubernetes', 'aws', 'ci/cd', 'terraform', 'jenkins', 'bash', 'monitoring'],
    salaryRange: '₹4.5–14 LPA entry (India)',
    demand: 'High',
    interests: ['cloud', 'devops', 'automation', 'infrastructure', 'linux'],
  },
  {
    title: 'Mobile App Developer',
    description: 'Creates native or cross-platform mobile applications.',
    skills: ['flutter', 'react native', 'kotlin', 'swift', 'android', 'ios', 'javascript', 'firebase', 'rest apis'],
    salaryRange: '₹4–11 LPA entry (India)',
    demand: 'Medium',
    interests: ['mobile', 'android', 'ios', 'apps'],
  },
  {
    title: 'UI/UX Designer',
    description: 'Designs intuitive product flows, wireframes and visual systems informed by user research.',
    skills: ['figma', 'wireframing', 'prototyping', 'user research', 'design systems', 'usability testing', 'ui/ux design'],
    salaryRange: '₹3.5–9 LPA entry (India)',
    demand: 'Medium',
    interests: ['design', 'ui', 'ux', 'creativity', 'user research'],
  },
  {
    title: 'Cybersecurity Analyst',
    description: 'Detects, investigates and prevents security threats across systems and networks.',
    skills: ['networking', 'linux', 'wireshark', 'burp suite', 'siem', 'penetration testing', 'owasp', 'python', 'incident response'],
    salaryRange: '₹4–12 LPA entry (India)',
    demand: 'Growing',
    interests: ['cybersecurity', 'security', 'hacking', 'ctf'],
  },
  {
    title: 'QA / Test Automation Engineer',
    description: 'Guards product quality through automated test suites and release checks.',
    skills: ['selenium', 'cypress', 'playwright', 'java', 'python', 'test automation', 'api testing', 'postman'],
    salaryRange: '₹3.5–8 LPA entry (India)',
    demand: 'Medium',
    interests: ['testing', 'quality assurance', 'automation'],
  },
  {
    title: 'Product Manager',
    description: 'Owns the what and why of a product — discovery, prioritization and delivery.',
    skills: ['communication', 'agile', 'user research', 'roadmapping', 'sql', 'analytics', 'stakeholder management'],
    salaryRange: '₹6–15 LPA entry (India)',
    demand: 'Medium',
    interests: ['product', 'business', 'strategy', 'leadership'],
  },
  {
    title: 'Business Analyst',
    description: 'Bridges business problems and technical solutions with requirements and data.',
    skills: ['sql', 'excel', 'power bi', 'requirement gathering', 'communication', 'analytics', 'statistics'],
    salaryRange: '₹3.5–9 LPA entry (India)',
    demand: 'Medium',
    interests: ['business', 'analytics', 'data', 'consulting'],
  },
  {
    title: 'Digital Marketing Specialist',
    description: 'Grows audiences and conversions through SEO, ads, content and analytics.',
    skills: ['seo', 'google ads', 'content marketing', 'social media', 'google analytics', 'email marketing', 'copywriting'],
    salaryRange: '₹2.5–7 LPA entry (India)',
    demand: 'Medium',
    interests: ['marketing', 'content', 'social media', 'branding'],
  },
];

export const INTERVIEW_BANK = {
  technical: [
    { question: 'Explain a technical project you built end-to-end. What was the hardest problem and how did you solve it?', focus: 'Depth of real experience', sampleAnswer: 'Situation: my team needed… Task: I owned the… Action: I designed…, profiled the bottleneck… Result: we cut latency 40% and shipped 2 weeks early.' },
    { question: 'How do you approach debugging something you have never seen before?', focus: 'Problem-solving method', sampleAnswer: 'I reproduce it first, then bisect: isolate layers, add logging, form one hypothesis at a time, and verify with the smallest possible test before fixing.' },
    { question: 'Walk me through how you would learn a brand-new technology in your first month on the job.', focus: 'Learning agility', sampleAnswer: 'I skim official docs for the mental model, build a tiny throwaway project, then read production code and ask a senior one focused question per day.' },
    { question: 'What tools and practices do you use to keep your work reliable and versioned?', focus: 'Engineering hygiene', sampleAnswer: 'Git with small PRs, writing tests for edge cases, linting in CI, and a short written design before anything non-trivial.' },
    { question: 'Describe the difference between a mistake you fixed quickly and one that cost the team. What changed?', focus: 'Accountability', sampleAnswer: 'A misconfigured env var I caught in review cost minutes; a missing validation reached users. I now add acceptance checks before merging anything user-facing.' },
  ],
  behavioral: [
    { question: 'Tell me about a time you disagreed with a teammate. How did you resolve it?', focus: 'Collaboration', sampleAnswer: 'STAR: we disagreed on the API design. I asked for their data, ran a 1-day spike of both options, and we picked based on measured latency — the relationship got stronger.' },
    { question: 'Describe your most significant failure. What did you learn?', focus: 'Self-awareness', sampleAnswer: 'I once over-engineered a feature nobody used. I learned to validate with users first; now I ship the smallest testable slice and iterate.' },
    { question: 'How do you prioritize when everything feels urgent?', focus: 'Prioritization', sampleAnswer: 'I list tasks with impact vs effort, confirm the real deadline with stakeholders, do the highest-impact unblocker first, and communicate the order openly.' },
    { question: 'Give an example of going beyond your assigned role.', focus: 'Ownership', sampleAnswer: 'Docs were stale and onboarding was painful, so I rewrote the setup guide and cut new-developer ramp-up from 3 days to half a day.' },
    { question: 'Why do you want this role specifically?', focus: 'Motivation fit', sampleAnswer: 'The role combines my strongest skill with the domain I want to grow in, and the team’s product solves a problem I have personally experienced.' },
  ],
  roleHints: {
    developer: { question: 'A page takes 6 seconds to load. Walk me through how you would diagnose and fix it.', focus: 'Performance thinking', sampleAnswer: 'Measure first: Lighthouse + network waterfall. Usually bundle size, unoptimized images or N+1 queries. I would fix the biggest measured cost, re-measure, and add a performance budget to CI.' },
    data: { question: 'You get a dataset with 15% missing values in a key column. What do you do?', focus: 'Data judgment', sampleAnswer: 'First understand why they are missing (MCAR/MAR/MNAR), quantify the pattern, then choose: impute with median/model, flag with an indicator column, or exclude — and report the choice’s impact on results.' },
    design: { question: 'How would you redesign a feature users ignore?', focus: 'User-centered thinking', sampleAnswer: 'Watch 3 users try it, find the drop-off, prototype the smallest change to the flow (not the pixels), and A/B test before rolling out.' },
    security: { question: 'You find a critical vulnerability on a Friday evening. What do you do?', focus: 'Incident process', sampleAnswer: 'Assess exploitability, contain (patch or WAF rule), escalate to the owner immediately regardless of the hour, document the timeline, and run a blameless postmortem with preventive actions.' },
  },
};
